OOPCPP Car class: MyCar::Car::upgradeEngine
upgradeEngine()
void MyCar::Car::upgradeEngine (unsigned int value)
{
         if(CarChecker::checkEnginePower(value)){
             setEnginePower(getEnginePower() + value);
         }
     }
References MyCar::CarChecker::checkEnginePower(), getEnginePower(), and setEnginePower().