OOPCPP Car class: MyCar::Car::operator=
operator=()
void MyCar::Car::operator= (const Car & object)
Copies object.
{
         CarChecker::checkInit(object, __FILE__, __LINE__);
         if(this->info == NULL){
             info = new CarPrivate;
         }
         this->setManufacturer(object.getManufacturer());
         this->setModel(object.getModel());
         this->setManufactureYear(object.getManufactureYear());
         this->setColor(object.getColor());
         this->setPlate(object.getPlate());
         this->setVin(object.getVin());
         this->setEnginePower(object.getEnginePower());
         this->setWeight(object.getWeight());
         this->setID(object.getID());
         this->info->fieldCount = object.info->fieldCount;
         ++instanceCount;
     }
References CarPrivate, MyCar::CarChecker::checkInit(), getColor(), getEnginePower(), getID(), getManufacturer(), getManufactureYear(), getModel(), getPlate(), getVin(), getWeight(), setColor(), setEnginePower(), setManufacturer(), setManufactureYear(), setModel(), setPlate(), setVin(), and setWeight().