OOPCPP Car class: MyCar::Car::Car
Car() [3/3]
MyCar::Car::Car (const Car & object)
{
         if(object.info == NULL){
             return;
         }
         info = new CarPrivate;
         this->setManufacturer(object.getManufacturer());
         this->setModel(object.getModel());
         this->setManufactureYear(object.getManufactureYear());
         this->setColor(object.getColor());
         this->setPlate(object.getPlate());
         this->setVin(object.getVin());
         this->setEnginePower(object.getEnginePower());
         this->setWeight(object.getWeight());
         this->setID(object.getID());
         this->info->fieldCount = object.info->fieldCount;
         ++instanceCount;
     }
References CarPrivate, getColor(), getEnginePower(), getID(), getManufacturer(), getManufactureYear(), getModel(), getPlate(), getVin(), getWeight(), setColor(), setEnginePower(), setManufacturer(), setManufactureYear(), setModel(), setPlate(), setVin(), and setWeight().