OOPCPP Car class: MyCar::Car::equals
equals()
bool MyCar::Car::equals (const Car & object)
Compares if objects are EXACTLY the same.
{
         if(this->getManufacturer() == object.getManufacturer() && this->getModel() == object.getModel() && this->getManufactureYear() == object.getManufactureYear() &&
            this->getColor() == object.getColor() && this->getPlate() == object.getPlate() && this->getVin() == object.getVin() && this->getEnginePower() == object.getEnginePower() &&
            this->getWeight() == object.getWeight() && this->getID() == object.getID()){
             return true;
         }else{
             return false;
         }
     }
References getColor(), getEnginePower(), getID(), getManufacturer(), getManufactureYear(), getModel(), getPlate(), getVin(), and getWeight().